services:
  postgres:
    container_name: postgres-sql-clinicalapp
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: clinicaldb
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  clinicalapp-backend:
    container_name: clinicalapp-backend
    image: ${BACKEND_IMAGE_NAME}
    ports:
      - 8088:8088
    networks:
      - spring-demo
    depends_on:
      - postgres
  # clinicalapp-frontend:
  #   container_name: clinicalapp-frontend
  #   image: clinicalapp/frontend:1.0.0
  #   ports:
  #     - 8080:80
  #   networks:
  #     - spring-demo
  #   depends_on:
  #     - clinicalapp-backend
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
