name: Clinicalapp_Frontend_Pipeline

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "infra/frontend/**"
      - "docker-compose.yml"
      - ".github/workflows/pipeline-frontend.yml"
  pull_request:
    branches:
      - main
jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      # - name: Exctract Project version
      #   id: extract_version
      #   run: |
      #     cd frontend
      #     echo "VERSION=1.0.0" >> $GITHUB_OUTPUT

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 --push \
            --tag ${{ secrets.DOCKER_USERNAME }}/clinicalapp-frontend:1.0.0 \
            --build-arg API_URL=${{ secrets.API_URL }} \
            -f infra/frontend/Dockerfile frontend
      - name: Set Docker Image Names
        id: set_image_names
        run: |
          echo "FRONTEND_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/clinicalapp-frontend:1.0.0" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    name: Deploy Frontend
    needs: [build-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      # - name: Exctract Project version
      #   id: extract_version
      #   run: |
      #     cd frontend
      #     echo "VERSION=1.0.0" >> $GITHUB_OUTPUT

      - name: Set Docker Image Names
        id: set_image_names
        run: |
          echo "FRONTEND_IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/clinicalapp-frontend:1.0.0" >> $GITHUB_OUTPUT

      - name: Create SSH Key File
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > keyfile.ppm

      - name: Set Key Permissions
        run: chmod 600 keyfile.ppm

      - name: Check SSH Connection
        run: ssh -i keyfile.ppm -o StrictHostKeyChecking=no ec2-user@${{ secrets.VPS_IP }} "echo SSH connection successful"

      - name: Create Deployment Folder
        run: ssh -i keyfile.ppm -o StrictHostKeyChecking=no ec2-user@${{ secrets.VPS_IP }} "mkdir -p ci-cd"

      - name: Copy Docker Compose File
        run: scp -i keyfile.ppm docker-compose.yml ec2-user@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml

      - name: Set environment variables and deploy
        run: |
          ssh -i keyfile.ppm -o StrictHostKeyChecking=no ec2-user@${{ secrets.VPS_IP }} <<EOF
          export FRONTEND_IMAGE_NAME=${{ steps.set_image_names.outputs.FRONTEND_IMAGE_NAME }}
          cd ci-cd
          docker-compose -f docker-compose.yml pull -q
          docker-compose -f docker-compose.yml up -d
          EOF